<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <meta name="author" content="Ashwin Nanjappa">
  <title>Code Yarns â€“ icu.InvalidArgsError</title>
  <style type="text/css">code{white-space: pre;}</style>
  <link rel="stylesheet" href="../styles.css">
  <!-- RSS feed -->
  <link rel="alternate" type="application/rss+xml" href="https://codeyarns.github.io/tech/rss.xml" />
  <!-- Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143311697-1">
  </script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'UA-143311697-1');
  </script>
  <!-- Google Adsense -->
  <script data-ad-client="ca-pub-6045459060677327" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js">
  </script>
</head>
<body>
<table style="width: 100%;">
    <tr>
        <td>
            <a href=".." class="header">Code Yarns &#128187;</a>
        </td>
        <td style="text-align: right;">
            <iframe src="https://duckduckgo.com/search.html?site=codeyarns.github.io&kp=-2&kc=1&prefill=Search this website" style="overflow:hidden;margin:0;padding:0;width:300px;height:40px;" frameborder="0"></iframe>
        </td>
    </tr>
</table>
<hr />
<header>
<h1 class="title">icu.InvalidArgsError</h1>
<p class="date">(First posted on: 2015-11-02 12:48:00+00:00)</p>
</header>
<h2 id="problem">Problem</h2>
<p>I tried running <strong>gcalcli</strong> and got this error:</p>
<pre><code>$ gcalcli
Traceback (most recent call last):
  File &quot;/usr/bin/gcalcli&quot;, line 392, in &lt;module&gt;
    class gcalcli:
  File &quot;/usr/bin/gcalcli&quot;, line 410, in gcalcli
    dateParser    = DateTimeParser()
  File &quot;/usr/bin/gcalcli&quot;, line 335, in __init__
    self.pdtCalendar = parsedatetime.Calendar();
  File &quot;/usr/lib/python2.7/dist-packages/parsedatetime/__init__.py&quot;, line 216, in __init__
    self.ptc = Constants()
  File &quot;/usr/lib/python2.7/dist-packages/parsedatetime/__init__.py&quot;, line 1733, in __init__
    self.locale = pdtLocales[&#39;icu&#39;](self.localeID)
  File &quot;/usr/lib/python2.7/dist-packages/parsedatetime/pdt_locales.py&quot;, line 151, in __init__
    self.icu = pyicu.Locale(localeID)
icu.InvalidArgsError: (&lt;type &#39;icu.Locale&#39;&gt;, &#39;__init__&#39;, (None,))</code></pre>
<h2 id="solution">Solution</h2>
<p>This is a well known bug in the <code>parsedatetime</code> package as described <a href="https://bugs.launchpad.net/ubuntu/+source/parsedatetime/+bug/1302963">here</a>.</p>
<p>The solution is to remove the package installed from Ubuntu archives and install a recent version of it from the Python Package Index:</p>
<pre><code>$ sudo apt-get remove python-parsedatetime

$ sudo pip install --upgrade parsedatetime</code></pre>
<p><strong>Tried with:</strong> Ubuntu 14.04</p>
<hr />
<p><a href="rss.xml">RSS</a> - <a href="mailto:codeyarns@gmail.com">Contact</a></p>
</body>
</html>
